import {Open_Sans} from "next/font/google";
// import { Hind_Siliguri } from "next/font/local";
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })
const sans=Open_Sans({
  subsets: ['cyrillic'],
  weight:['300','400','500','600','700'],
  variable:"--font-sans"
})
// const shiliguri=Hind_Siliguri({
//   src:"./Fonts/HindSiliguri-Regular.ttf",
//   variable:"--font-Shiliguri"
// })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sans.variable} `} >{children}</body>
    </html>
  )
}
